etranger/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^payment/', include('payment.urls')),
]

payment/urls.py
from django.conf.urls import url

from . import views
 
app_name = 'payment'
urlpatterns = [        
	url(r'^$', views.CreatePayment.as_view(), name='createpayment'), 
	url(r'^index/$', views.ListPayment.as_view(), name='index'), 
	url(r'^addpayment/$', views.addpayment, name='addpayment'), 
<<<<<<< HEAD
 
=======
	url(r'^paymentdetail/(?P<pk>\d+)/$', views.DetailPayment.as_view(), name='paymentdetail'), 
>>>>>>> paymentdev
]

payment/models.py
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django.db import models

CURRENCY_CHOICES = (

    ('USD', 'USD'),
    ('EURO', 'EURO'),
)

ORDER_CHOICES = (
    ('BENEFICIAIRE', 'BENEFICIAIRE'),
    ('PRINCIPAL', 'PRINCIPAL'),
 
)

class  Paymentorder(models.Model):
    monnaie = models.CharField(max_length=5, choices = CURRENCY_CHOICES,verbose_name=_(u'Monnaie'),default = "EURO")
    amountchiffre=models.FloatField(verbose_name=_(u' Montant en chiffres'))
    beneficiary = models.CharField(max_length=256,verbose_name=_(u'Beneficaire '))
    address = models.TextField(max_length=256, verbose_name=_(u'Adresse du beneficiaire'))
    bank = models.CharField(max_length=256, verbose_name=_(u'Banque'))
    accountbank = models.CharField(max_length=256, verbose_name=_(u'Numero de Compte '))
    ibancode = models.CharField(max_length=256, verbose_name=_(u' Code Iban   '))
    swiftcode = models.CharField(max_length=256, verbose_name=_(u'Code SWIFT'))
    addressbank = models.TextField(max_length=256, verbose_name=_(u'Adresse de la Banque'))
    amountletter = models.CharField(max_length=256, verbose_name=_(u'Montant en lettres'))
    detailpayment = models.TextField(max_length=256, verbose_name=_(u'Detals de paiement'))
    datepayment = models.DateTimeField(auto_now_add=True, verbose_name=_(u'Date'))
    principal  = models.CharField(max_length=256, verbose_name=_(u"Donneur d'ordre"))
    accountnumber = models.CharField(max_length=20, verbose_name=_(u'Numero de Compte'))
    ciostopay = models.CharField(max_length=20, choices = ORDER_CHOICES,verbose_name=_(u'Frais lies au transfert '),default = 'BENEFICIAIRE')




    def __str__(self):
           return self.monnaie


    class Meta:
         db_table = "paymentorder"

payment/forms.py
from django import forms
from payment.models import  Paymentorder

class PaymentForm(forms.ModelForm):
     class Meta:
        model = Paymentorder
        fields = '__all__'

payment/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect, HttpResponse
from django.utils import timezone
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from payment.forms import * 
from payment.models import *

class CreatePayment(CreateView):
    model=Paymentorder
    #fields = "__all__"
    form_class=PaymentForm
    template_name='payment/createpayment.html'
    #context_object_name = "payment"
    
    def get_object(self):
 
       return super(CreatePayment, self).get_object()

    
 
    def get_success_url(self):
        return reverse('payment:index')

    def get_context_data(self, **kwargs):
        context = super(CreatePayment, self).get_context_data(**kwargs)
        context['action'] = reverse('payment:index')
        return context

class ListPayment(ListView):
    model=Paymentorder
    #form_class=PaymentForm
    template_name='payment/index.html'
    context_object_name = "payment"
    
    def get_queryset(self):
       return Paymentorder.objects.all().order_by('-amountchiffre')

    def get_success_url(self):
        return reverse('payment:index')

    def get_context_data(self, **kwargs):
        context = super(ListPayment, self).get_context_data(**kwargs)
        context['action'] = reverse('payment:index')
        return context


class DetailPayment(DetailView):
    model=Paymentorder
    template_name='payment/paymentdetail.html'
    context_object_name = "payment"


def  addpayment(request):
	 
    if request.method=='POST':
  
        trs = Paymentorder.objects.create( monnaie=request.POST['monnaie'], amountchiffre=request.POST['amountchiffre'],beneficiary=request.POST['beneficiary'], address=request.POST['address'], bank=request.POST['bank'],accountbank = request.POST['accountbank'], amountletter=request.POST['amountletter'], detailpayment=request.POST['detailpayment'], principal=request.POST['principal'], accountnumber=request.POST['accountnumber'],ciostopay=request.POST['ciostopay'],ibancode=request.POST['ibancode'], swiftcode=request.POST['swiftcode'],addressbank=request.POST['ciostopay'])
        trs.save()
	return render(request, 'payment/addpayment.html', {'trs':trs})
                  
    else:
        form=PaymentForm()
        return render(request, 'payment/addpayment.html', {'form':form})

payment/templates/payment/addpayment.html
  <body>
    
<center> 
{% if form %}
<form   method="post">
        <h2>Welcome to the payment page<br><br> </h2>

        {% csrf_token %}
 
        {{ form.as_p }}
 <input type="submit" value="Transférer"> 
</form>
{% endif %}
{% if trs %}
<br><br><br>
<h1> Detail de payement :<br><br/> </h1>
<table border="0">
  <tr>
      <p><td>Monnaie</td><td>{{ trs.monnaie }} </td></p>
  </tr><tr>
      <p><td>Montant en chiffres</td><td>{{ trs.amountchiffre }}</p></td>
  </tr>

  <tr>
      <p><td>Beneficiaire & Adresse</td><td>{{ trs.beneficiary }} {{ trs.address }}</p></td>
  </tr>

  <tr><p><td>Banque  & No de Compte</td><p><td> {{ trs.bank }} {{ trs.accountbank }}</td></p></tr>
  <tr><p><td>Iban Code & Code SWIFT</td><td>{{ trs.ibancode }}  {{ trs.swiftcode }}  </td></p></tr>
  <tr><p><td>Adresse de la Banque</td><td>{{ trs.addressbank }}  </td></p></tr>
  <tr><p><td>Montant en lettres</td><td>{{ trs.amountletter }}  </td></p></tr>
  <tr><p><td>Details de paiement</td><td>{{ trs.detailpayment }}  </td></p></tr>
  <tr><p><td>Donneur d'ordre</td><td>{{ trs.principal }} </td></p></tr>
  <tr><p><td>Numéro de Compte</td><td>{{ trs.accountnumber }} </td></p></tr>
  <tr><p><td>Commissions</td><td>{{ trs.ciostopay }} </td></p></tr>
 
</table>
 <br><br><br> <a href="{% url 'payment:addpayment' %}"  > Add a new payment</a>
 <br><br><br> <a href="{% url 'payment:index' %}"  > List payment   </a>
{% endif %}
 </body>

payment/templates/payment/createpayment.html
<body>
<h1> Bienvenu au formulaire de paiement a l'INTERBANK BURUNDI</h1>
{#% if payment % #}

<form method="post" >
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="save">
</form>

{#% endif  %#}
</body>

payment/templates/payment/index.html
<center>
<h1>Details des ordres de payment :<br><br></h1>


<table border="3"> 
 
<tr><th>Monnaie </th><th>Montant en chiffres</th><th>Beneficiaire & Adresse</th><th>Banque  & No de Compte</th><th>Montant en lettres</th><th> Details de paiement </th><th>Date</th><th>Donneur d'ordre</th><th>Numéro de Compte</th><th>Commissions</th><th>Look a Detail </th></tr>
 {% for pay in payment %}
<tr><td>{{ pay.monnaie }}</td><td>{{ pay.amountchiffre }} </td><td>{{ pay.beneficiary }}  {{ pay.address }}</td><td>{{ pay.bank }} {{ pay.accountbank }}</td><td>{{ pay.amountletter }}</td><td>{{ pay.detailpayment }}</td><td>{{ pay.datepayment }}</td><td>{{ pay.principal }}</td><td>{{ pay.accountnumber }}</td><td>{{ pay.ciostopay }}</td><td><a href="{% url 'payment:paymentdetail' pk=pay.id %}">{{ pay.principal }}</a></td></tr>
 {% endfor %}
</table>
</div>
<br><br> <a href="{% url 'payment:createpayment' %}"  > Add a new payment</a>

 
</center>

payment/templates/payment/paymentdetail.html
<center> 
{% if payment %}

 
<h1> Detail de payment :<br><br/> </h1>
<table border="0">
  <tr>
      <p><td>Monnaie</td><td>{{ payment.monnaie }}   </td></p>
  </tr><tr>
      <p><td>Montant en chiffres</td><td>{{ payment.amountchiffre }}</p></td>
  </tr>

  <tr><p><td>Beneficiaire & Adresse</td><p><td>{{ payment.bank }}, {{ payment.accountbank }}</td></p></tr>
  <tr>
      <p><td>Banque & No de Compte   </td><td>{{ payment.beneficiary }},  {{ payment.address }} </p></td>
  </tr>
  <tr>
      <p><td>IbanCode , Code SWIFT  & Adresse Banque </td><td>  {{ payment.ibancode }},  {{ payment.swiftcode }},  {{ payment.addressbank }}</p></td>
  </tr>
  <tr>
      <p><td>Montant en lettres</td><td>{{ payment.amountletter }}</p></td>
  </tr>
  <tr><p><td> Details de paiement </td><td>{{ payment.detailpayment }} </td></p></tr>
  <tr><p><td>Date</td><p><td>{{ payment.datepayment }}</td></p></tr>
  <tr><p><td>Donneur d'ordre</td><p><td>{{ payment.principal }}</td></p></tr>
  <tr><p><td>Numéro de Compte</td><p><td>{{ payment.accountnumber }}</td></p></tr>
  <tr><p><td>Frais liés au transfert</td><p><td>{{ payment.ciostopay }}</td></p></tr> 
 
</table>
{% endif %}                        
 </center> 